api/urls.py
from django.urls import path
from api import views

urlpatterns = [
	path('flight/', views.index, name='index')
]

flight_api/urls.py
from django.contrib import admin
from django.urls import path, include
from .import settings
from django.contrib.staticfiles.urls import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
	path('api/', include('api.urls')),
    path('admin/', admin.site.urls),
]

urlpatterns += staticfiles_urlpatterns()

api/models.py
from django.db import models

# Create your models here.
"""
class Leg(models.Model):
    time_of_departure = models.TimeField()
    time_of_arrival = models.TimeField()
    date_of_departure = models.DateField()
    date_of_arrival = models.DateField()
    business_class_ticket_num = models.IntegerField()
    economy_class_ticket_num = models.IntegerField()

    def __str__(self):
        return "Date: "+str(self.date_of_departure)+" - "+str(self.date_of_arrival)+" || "+"Date: "+str(self.time_of_departure)+" - "+str(self.time_of_arrival)
"""
class Flight(models.Model):
    departure = models.CharField(max_length=30)
    arrival = models.CharField(max_length=30)
    #legs = models.ManyToManyField(Leg)
    price = models.FloatField(default=174.2)
    time_of_departure = models.TimeField()
    time_of_arrival = models.TimeField()
    date_of_departure = models.DateField()
    date_of_arrival = models.DateField()
    business_class_ticket_num = models.IntegerField()
    economy_class_ticket_num = models.IntegerField()

    def __str__(self):
        return "Flight: "+str(self.departure)+" - "+str(self.arrival)

api/forms.py
from django import forms

Tavel_Class_Options = [
    ('First', 'First'),
    ('Economy', 'Economy'),
    ('Premium', 'Premium'),
    ('Business', 'Business'),
]

Trip_Type_Options = [
    ('roundtrip', "roundtrip"),
    ('oneway', "oneway"),
]

Count_Options = [
    (0, 0),
    (1, 1),
    (2, 2),
    (3, 3),
    (4, 4),
    (5, 5),
    (6, 6),
    (7, 7),
    (8, 8),
    (9, 9),
    (10, 10),
]
Adult_Count_Options = [
    (1, 1),
    (2, 2),
    (3, 3),
    (4, 4),
    (5, 5),
    (6, 6),
    (7, 7),
    (8, 8),
    (9, 9),
    (10, 10),
]
Departure_Option = [
	("label", "City or airport"),
	("Abuja", "Abuja (ABV)"),
    ("Accra", "Accra (ACC)"),
    ("Ahmedabad", "Ahmedabad (AMD)"),
    ("Akure", "Akure (AKR)"),
    ("Almaty", "Almaty (ALA)"),
    ("Amman", "Amman (AMM)"),
    ("Asaba", "Asaba (ABB)"),
    ("Baku", "Baku (GYD)"),
    ("Bangalore", "Bangalore (BLR)"),
    ("Banjul", "Banjul (BJL)"),
    ("Beirut", "Beirut (BEY)"),
    ("Benin", "Benin (BNI)"),
    ("Enugu", "Enugu (ENU)"),
    ("Kaduna", "Kaduna (KAD)"),
    ("Kano", "Kano (KAN)"),
    ("Lagos", "Lagos (LOS)"),
    ("Owerri", "Owerri (QOW)"),
    ("Port Harcourt", "Port Harcourt (PHC)"),
    ("Uyo", "Uyo (QUO)"),
    ("Warri", "Warri (QRW)"),
    ("YOL", "Yola (YOL)"),
]

Arrival_Option = [
	("label", "Flyning to"),
]


class BookingForm(forms.Form):
    trip_type = forms.CharField(label='Enter Trip Type', widget=forms.Select(choices=Trip_Type_Options, attrs={'class':'off'} ))
    departure = forms.CharField(label='Enter Departure Location', widget=forms.Select(choices=Departure_Option, attrs={"class":"form-control"} ))
    arrival = forms.CharField(label='Enter Arrival Location', widget=forms.Select(choices=Arrival_Option, attrs={"class":"form-control"} ))
    departure_date = forms.DateField(widget=forms.DateInput(format='%m/%d/%Y', attrs={'class': 'form-control'}),input_formats=('%d/%m/%Y', ))
    return_date = forms.DateField(widget=forms.DateInput(format='%m/%d/%Y', attrs={'class': 'form-control'}),input_formats=('%d/%m/%Y', ), required=False)
    adultcount = forms.IntegerField(label='Enter Adult Count', widget=forms.Select(choices=Adult_Count_Options, attrs={"class":"form-control"} ))
    child_count = forms.IntegerField(label='Enter Child Count', widget=forms.Select(choices=Count_Options, attrs={"class":"form-control"} ))
    infant_count = forms.IntegerField(label='Enter Infant Count', widget=forms.Select(choices=Count_Options, attrs={"class":"form-control"} ))
    travel_class = forms.CharField(label='Enter Travel Class', widget=forms.Select(choices=Tavel_Class_Options, attrs={"class":"form-control"} ))

    def clean_departure(self):
    	data = self.cleaned_data['departure']
    	if(data == "label"):
    		raise forms.ValidationError('You have to select departure')
    	return data

    def clean_arrival(self):
    	data = self.cleaned_data['arrival']
    	if(data == "label"):
    		raise forms.ValidationError('You have to select arrival')
    	return data

    def clean_return_date(self):
    	data = self.cleaned_data
    	trip_type_data = self.cleaned_data['trip_type']
    	if(trip_type_data == "roundtrip" and not data['return_date']):
    		raise forms.ValidationError('You have to select return date for a round trip')
    	return data

api/views.py
from django.shortcuts import render
from .forms import BookingForm
from django.http import HttpResponse
from .models import *

# Create your views here.
def index(request):
	if request.method == 'POST':
		form = BookingForm(request.POST)
		if form.is_valid():
			departure = form.cleaned_data['departure']
			arrival = form.cleaned_data['arrival']
			departure_date = form.cleaned_data['departure_date']
			adult = form.cleaned_data['adultcount']

			q = Flight.objects.filter(departure=departure)
			q = q.filter(arrival=arrival)
			q = q.filter(date_of_departure=departure_date)
			print("====================================")
			print(departure)
			print(arrival)
			print(q)
			return render(request, 'api/flight-results-1 - Copy.html', {'flights':q})

	else:
		form = BookingForm()
	flights = Flight.objects.all
	temp = 'api/index2.html'
	ct = {'form':form, 'flights':flights}
	return render(request, temp, ct)

def flight_list(request):
	pass

api/templates/api/index.html
<!DOCTYPE html>
<html>
<head>
	<title>api</title>
</head>
<body>
<h2>Flight API</h2>
<!--
<form action="" method="post">
    {% csrf_token %}
    {{ form }}
    <input type="submit" value="Submit">
</form>-->

<form method="post" novalidate>
  {% csrf_token %}

  {{ form.non_field_errors }}

  {% for hidden_field in form.hidden_fields %}
    {{ hidden_field.errors }}
    {{ hidden_field }}
  {% endfor %}

  <table border="1">
    {% for field in form.visible_fields %}
      <tr>
        <th>{{ field.label_tag }}</th>
        <td>
          {{ field.errors }}
          {{ field }}
          {{ field.help_text }}
        </td>
      </tr>
    {% endfor %}
  </table>

  <button type="submit">Submit</button>
</form>


<script
  src="https://code.jquery.com/jquery-3.4.1.min.js"
  integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo="
  crossorigin="anonymous"></script>
<script type="text/javascript">
	flights = [
	{% for flight in flights %}
		{% if not forloop.last %}
	         {'form':'{{flight.departure}}', 'to':'{{flight.arrival}}'},
	      {% else %}
	         {'form':'{{flight.departure}}', 'to':'{{flight.arrival}}'}
	      {% endif %}
	{% endfor %}
	]

	$(function() {
		populate_arrival(flights);
	  $( "#id_departure" ).change(function() {
		  populate_arrival(flights);
		});
	});

	function populate_arrival(data){
		$('#id_arrival')
		    .find('option')
		    .remove()
		    .end()
		    .append('<option value="to">To</option>');

		data.forEach(function(e, i){
			if(e.form == $("#id_departure").val()){
				$('#id_arrival').append($('<option><option/>').val(e.to).text(e.to));
			}
		});
		$("#id_arrival option").each(function (idx, val) {
	       $(this).siblings("[value='" + $(this).val() + "']").remove();
	  });
	}
</script>
</body>
</html>

api/templates/api/index2.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<!-- Mirrored from colorlib.com/etc/bforms/colorlib-booking-19/ by HTTrack Website Copier/3.x [XR&CO'2014], Wed, 27 Nov 2019 11:49:33 GMT -->
<!-- Added by HTTrack --><meta http-equiv="content-type" content="text/html;charset=UTF-8" /><!-- /Added by HTTrack -->
<head>
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1">

<title>Booking Form HTML Template</title>

<link href="https://fonts.googleapis.com/css?family=Lato:400,700" rel="stylesheet">

<link type="text/css" rel="stylesheet" href="{% static 'index_assets/css/bootstrap.min.css' %}" />

<link type="text/css" rel="stylesheet" href="{% static 'index_assets/css/style.css' %}" />

<link type="text/css" rel="stylesheet" href="{% static 'index.css' %}" />


<!--[if lt IE 9]>
		  <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
		  <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
		<![endif]-->
</head>
<body>
<div id="booking" class="section">
	<div class="section-center">
	<div class="container">
		<div class="row">
			<div class="col-md-4">
				<div class="booking-cta">
					<h1>Book your flight today</h1>
					<p>Date format: dd/mm/yyyy</p>
					<p>Dummy data: Abuja to Accra and Accra to Abuja</p>
					<p>Date for all flights: 15/12/2019</p>
					<p>username: admin, password: pass1234</p>
				</div>
			</div>
				<div class="col-md-7 col-md-offset-1">
					<div class="booking-form">
						<form action="" method="post">
							{% csrf_token %}
							<div class="form-group">
								<span style="color: red">
								{{ form.travel_class.errors }}
								{{ form.infant_count.errors }}
								{{ form.child_count.errors }}
								{{ form.adultcount.errors }}
								{{ form.return_date.errors }}
								{{ form.departure_date.errors }}
								{{ form.arrival.errors }}
								{{ form.departure.errors }}
								{{ form.trip_type.errors }}
								{{ form.non_field_errors }}
							</span>
								<div class="form-checkbox">
									<label for="roundtrip">
										Trip Type:
										{{ form.trip_type }}
										<span></span>
									</label>
									<!--
									<label for="one-way">
										<input type="radio" id="one-way" name="flight-type">
										<span></span>One way
									</label>-->

								</div>
							</div>
							<div class="row">
								<div class="col-md-6">
									<div class="form-group">
										<span class="form-label">Flying from</span>
										<!--<input class="form-control" type="text" placeholder="City or airport">-->
										{{ form.departure }}
									</div>
								</div>
								<div class="col-md-6">
									<div class="form-group">
										<span class="form-label">Flyning to</span>
										{{ form.arrival }}
									</div>
								</div>
							</div>
							<div class="row">
								<div class="col-md-6">
									<div class="form-group">
										<span class="form-label">Departing</span>
										{{ form.departure_date}}
									</div>
								</div>
								<div class="col-md-6">
									<div class="form-group">
										<span class="form-label">Returning</span>
										<!--
										<input class="form-control" type="date" required>-->
										{{ form.return_date }}
									</div>
								</div>
							</div>
							<div class="row">
								<div class="col-md-3">
									<div class="form-group">
										<span class="form-label">Adults (12+)</span>
										<!--
										<select class="form-control">
											<option>1</option>
											<option>2</option>
											<option>3</option>
										</select>-->
										{{form.adultcount}}
										<span class="select-arrow"></span>
									</div>
								</div>
								<div class="col-md-3">
									<div class="form-group">
										<span class="form-label">Children (2-12)</span>
										<!--
										<select class="form-control">
											<option>0</option>
											<option>1</option>
											<option>2</option>
										</select>-->
										{{form.child_count}}
										<span class="select-arrow"></span>
									</div>
								</div>
								<div class="col-md-3">
									<div class="form-group">
										<span class="form-label">Infant (0-2)</span>
										<!--
										<select class="form-control">
											<option>0</option>
											<option>1</option>
											<option>2</option>
										</select>-->
										{{form.infant_count}}
										<span class="select-arrow"></span>
									</div>
								</div>
								<div class="col-md-3">
									<div class="form-group">
										<span class="form-label">Travel class</span>
										<!--
										<select class="form-control">
											<option>Economy class</option>
											<option>Business class</option>
											<option>First class</option>
										</select>-->
										{{form.travel_class}}
										<span class="select-arrow"></span>
									</div>
								</div>
							</div>
							<div class="form-btn">
								<input class="submit-btn" type="submit" value="Submit" />
							</div>
						</form>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>

<!-- 0000000000000000000 -->
<script
  src="https://code.jquery.com/jquery-3.4.1.min.js"
  integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo="
  crossorigin="anonymous"></script>
<script type="text/javascript">
	flights = [
	{% for flight in flights %}
		{% if not forloop.last %}
	         {'form':'{{flight.departure}}', 'to':'{{flight.arrival}}'},
	      {% else %}
	         {'form':'{{flight.departure}}', 'to':'{{flight.arrival}}'}
	      {% endif %}
	{% endfor %}
	]

	$(function() {
		populate_arrival(flights);
	  $( "#id_departure" ).change(function() {
		  populate_arrival(flights);
		});
	});

	function populate_arrival(data){
		$('#id_arrival')
		    .find('option')
		    .remove()
		    .end()
		    .append('<option value="label">Flyning to</option>');

		data.forEach(function(e, i){
			if(e.form == $("#id_departure").val()){
				$('#id_arrival').append($('<option><option/>').val(e.to).text(e.to));
			}
		});
		$("#id_arrival option").each(function (idx, val) {
	       $(this).siblings("[value='" + $(this).val() + "']").remove();
	  });
	}
</script>
<!-- 9999999999999999999 -->

<script async src="https://www.googletagmanager.com/gtag/js?id=UA-23581568-13" type="2868c1b95c1dda0dbbcc7618-text/javascript"></script>
<script type="2868c1b95c1dda0dbbcc7618-text/javascript">
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'UA-23581568-13');
</script>
<script src="../../../../ajax.cloudflare.com/cdn-cgi/scripts/7089c43e/cloudflare-static/rocket-loader.min.js" data-cf-settings="2868c1b95c1dda0dbbcc7618-|49" defer=""></script></body>

<!-- Mirrored from colorlib.com/etc/bforms/colorlib-booking-19/ by HTTrack Website Copier/3.x [XR&CO'2014], Wed, 27 Nov 2019 11:49:34 GMT -->
</html>